/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "on-primary": "#ffffff",
        "surface-bright": "#fff8f6",
        "surface-container-highest": "#f4ded7",
        "inverse-surface": "#3a2e29",
        "surface-container-high": "#fae4dd",
        "surface-tint": "#a43c12",
        "on-tertiary-fixed": "#001e2e",
        "on-primary-container": "#6c2000",
        "tertiary-container": "#61acda",
        "error-container": "#ffdad6",
        "surface-container-low": "#fff1ec",
        "primary-container": "#ff7f50",
        "primary-fixed-dim": "#ffb59c",
        "surface-container": "#ffe9e3",
        "on-secondary": "#ffffff",
        "on-surface-variant": "#57423b",
        "on-primary-fixed-variant": "#822800",
        "error": "#ba1a1a",
        "background": "#fff8f6",
        "secondary-fixed-dim": "#59dad1",
        "secondary-container": "#76f3ea",
        "on-background": "#241915",
        "on-tertiary-container": "#003e5a",
        "primary": "#a43c12",
        "on-error-container": "#93000a",
        "outline-variant": "#dec0b6",
        "on-secondary-fixed": "#00201e",
        "outline": "#8b7169",
        "secondary-fixed": "#79f6ed",
        "surface-variant": "#f4ded7",
        "secondary": "#006a65",
        "inverse-primary": "#ffb59c",
        "surface": "#fff8f6",
        "inverse-on-surface": "#ffede8",
        "tertiary-fixed": "#c7e7ff",
        "on-secondary-container": "#006f69",
        "surface-dim": "#ebd6cf",
        "on-error": "#ffffff",
        "tertiary": "#00658e",
        "tertiary-fixed-dim": "#85cfff",
        "on-primary-fixed": "#380c00",
        "primary-fixed": "#ffdbcf",
        "on-secondary-fixed-variant": "#00504c",
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#241915",
        "on-tertiary-fixed-variant": "#004c6c"
      },
      "borderRadius": {
        "DEFAULT": "8px",
        "lg": "12px",
        "xl": "16px",
        "full": "9999px"
      },
      "spacing": {
        "brand-sm": "8px",
        "brand-lg": "24px",
        "brand-base": "4px",
        "brand-md": "16px",
        "brand-margin-desktop": "64px",
        "brand-margin-mobile": "16px",
        "brand-gutter": "24px",
        "brand-xs": "4px",
        "brand-xl": "40px"
      },
      "fontFamily": {
        "headline-lg": ["Manrope"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"],
        "display-lg": ["Manrope"],
        "headline-lg-mobile": ["Manrope"],
        "label-md": ["JetBrains Mono"],
        "label-sm": ["JetBrains Mono"],
        "headline-md": ["Manrope"]
      },
      "fontSize": {
        "headline-lg": ["32px", {"lineHeight": "1.2", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "display-lg": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "1.2", "fontWeight": "600"}],
        "label-md": ["14px", {"lineHeight": "1.4", "letterSpacing": "0.05em", "fontWeight": "500"}],
        "label-sm": ["12px", {"lineHeight": "1.4", "fontWeight": "500"}],
        "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}]
      },
      "maxWidth": {
        "xs": "20rem",
        "sm": "24rem",
        "md": "28rem",
        "lg": "32rem",
        "xl": "36rem",
        "2xl": "42rem",
        "3xl": "48rem",
        "4xl": "56rem",
        "5xl": "64rem",
        "6xl": "72rem",
        "7xl": "80rem",
      }
    },
  },
  plugins: [],
}
